# Generated by Django 5.1.7 on 2025-03-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formcode', models.CharField(max_length=20)),
                ('problem_date', models.DateTimeField()),
                ('production_stop', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=50)),
                ('machine_name', models.CharField(max_length=50)),
                ('machine_code', models.CharField(max_length=50)),
                ('machine_place_code', models.CharField(max_length=50)),
                ('failure_time', models.CharField(max_length=50)),
                ('shift', models.CharField(max_length=50)),
                ('suggest_time', models.CharField(max_length=50)),
                ('work_suggest', models.CharField(max_length=50)),
                ('fix_repair', models.CharField(max_length=50)),
                ('report_inseption', models.CharField(max_length=50)),
                ('fault_dm', models.CharField(max_length=50)),
                ('operator_name', models.CharField(max_length=50)),
            ],
        ),
    ]
