# Generated by Django 5.1.6 on 2025-03-16 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitform',
            old_name='report_inseption',
            new_name='report_inspection',
        ),
        migrations.AddField(
            model_name='submitform',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitforms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submitform',
            name='problem_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='submitform',
            name='stop_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='failure_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='problem_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='suggest_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
