# Generated by Django 5.1.6 on 2025-03-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_submitform_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitform',
            old_name='failure_time',
            new_name='failuretime',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='fault_dm',
            new_name='faultdm',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='fix_repair',
            new_name='fixrepair',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='machine_code',
            new_name='machinecode',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='machine_name',
            new_name='machinename',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='machine_place_code',
            new_name='machineplacecode',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='operator_name',
            new_name='operatorname',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='problem_date',
            new_name='problemdate',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='problem_description',
            new_name='problemdescription',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='production_stop',
            new_name='productionstop',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='report_inspection',
            new_name='reportinspection',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='stop_time',
            new_name='stoptime',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='suggest_time',
            new_name='suggesttime',
        ),
        migrations.RenameField(
            model_name='submitform',
            old_name='work_suggest',
            new_name='worksuggest',
        ),
    ]
