# Generated by Django 5.1.6 on 2025-03-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_failure_time_submitform_failuretime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='problemdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='stoptime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
