# Generated by Django 5.1.6 on 2025-03-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_submitform_problemdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='failuretime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='suggesttime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
