# Generated by Django 5.1.6 on 2025-03-17 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_submitform_failuretime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitform', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='failuretime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='problemdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='stoptime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='suggesttime',
            field=models.TimeField(null=True),
        ),
    ]
