# Generated by Django 5.1.6 on 2025-03-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_submitform_author_alter_submitform_problemdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='problemdate',
            field=models.DateField(null=True),
        ),
    ]
