# Generated by Django 5.1.6 on 2025-03-17 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_submitform_problemdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitform', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='faultdm',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='fixrepair',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='formcode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machinecode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machinename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machineplacecode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='operatorname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='problemdescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='productionstop',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='reportinspection',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='section',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='shift',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='worksuggest',
            field=models.CharField(max_length=100),
        ),
    ]
