# Generated by Django 5.1.6 on 2025-03-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_submitform_problemdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitform',
            name='unit',
            field=models.CharField(default='مکانیک', max_length=20),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machineplacecode',
            field=models.CharField(default='MDF1', max_length=100),
        ),
    ]
