# Generated by Django 5.1.6 on 2025-03-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_submitform_unit_alter_submitform_machineplacecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='fixrepair',
            field=models.CharField(default='درخواست اپراتور', max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='reportinspection',
            field=models.CharField(default='بازرسی فنی', max_length=100),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='suggesttime',
            field=models.CharField(default='فوری', max_length=30),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='worksuggest',
            field=models.CharField(default='اظطراری', max_length=100),
        ),
    ]
