# Generated by Django 5.1.6 on 2025-03-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_submitform_fixrepair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='stoptime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
