# Generated by Django 5.1.6 on 2025-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_loginform'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginform',
            name='role',
            field=models.CharField(default='Admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginform',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loginform',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
