# Generated by Django 5.1.6 on 2025-03-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_submitform_fixrepair_alter_submitform_formcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitform',
            name='formcode',
            field=models.CharField(max_length=100),
        ),
    ]
