# Generated by Django 5.1.6 on 2025-03-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_submitform_formcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitform',
            name='unit',
        ),
        migrations.AlterField(
            model_name='submitform',
            name='faultdm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='fixrepair',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='formcode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machinecode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='machinename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='operatorname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='productionstop',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='reportinspection',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='shift',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='submitform',
            name='worksuggest',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
