// export { default as Login } from "./Login";
export { default as Dashboard } from "./Dashboard";
export { default as SubmitForm } from "./SubmitForm";
export { default as OperatorDashboard } from "./OperatorDashboard";
export { default as OperatorSubmit } from "./OperatorSubmit";
export { default as OperatorLogin } from "./OperatorLogin";
export { default as TechnicianSubmit } from "./TechnicianSubmit";
export { default as TechnicianLogin } from "./TechnicianLogin";
export { default as Technician } from "./Technician";
export { default as TechnicianDashboard } from "./TechnicianDashboard";
export { default as PmForms } from "./PmForms";
export { default as PmSubmit } from "./PmSubmit";
// export { default as Start } from "./Start";
export { default as Forms } from "./Forms";
export { default as Login } from "./Login";
export { default as Start } from "./Start";
export { default as Register } from "./Register";
export { default as Aghlam } from "./Aghlam";
export { default as NotFound } from "./NotFound";
